const {chromium}=require(process.env.EQC_PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('pageerror',e=>errors.push(e.message));
 const p={id:'research',name:'Research QA',createdAt:1,folders:[],docs:[{id:'d',name:'FGD',content:'Alice discusses water costs.\nBob discusses drainage failures.',addedAt:1,folderId:null}],codes:[{id:'a',name:'Water',parentId:null,color:'#2563eb',summary:'Water memo',createdAt:1},{id:'b',name:'Cost',parentId:null,color:'#ea580c',summary:'',createdAt:1}],codedSegments:[{id:'s',docId:'d',codeId:'a',start:16,end:21,text:'water',coder:'Ann',note:'Check affordability',createdAt:1}],images:[],codedRegions:[]};
 await page.addInitScript(p=>{
  localStorage.setItem('qda-document-view','text');
  const earned=Number(localStorage.getItem('eqc-qa-earned-minutes'));if(earned){const store=JSON.parse(localStorage.getItem('eqc-profiles-v2')),active=store.profiles.find(p=>p.id===store.activeId),r=active.records.find(r=>r.codingMs>0);r.codingMs=earned*60000;r.appMs=Math.max(r.appMs,r.codingMs);r.end=Math.max(r.end,r.start+r.appMs);localStorage.setItem('eqc-profiles-v2',JSON.stringify(store));}
window.__qaProject=p;window.__exports=[];window.__checkpoints=[];
  const record=async(...args)=>{window.__exports.push(args);return 'synthetic-export';};
  window.qv=new Proxy({listProjects:async()=>[{id:p.id,name:p.name}],loadProject:async()=>window.__qaProject,saveProject:async p=>{window.__qaProject=structuredClone(p);return p;},exportText:record,exportDocxTable:record,exportBackup:record,importBackup:async()=>window.__nextImport,
   projectHistory:async()=>({activity:[{id:1,at:1,actor:'Ann',summary:'1 text coding added'}],snapshots:window.__checkpoints.map(s=>({id:s.id,at:1,label:s.label,automatic:false,sizeBytes:2000}))}),
   createCheckpoint:async(_,label)=>{window.__checkpoints.push({id:window.__checkpoints.length+1,label,data:structuredClone(window.__qaProject)});return window.qv.projectHistory();},readSnapshot:async(_,id)=>window.__checkpoints.find(s=>s.id===id).data,
   lan:new Proxy({},{get:(_,n)=>String(n).startsWith('on')?()=>{}:async()=>({ok:true})})},{get:(t,n)=>t[n]||(String(n).startsWith('on')?()=>{}:async()=>null)});
 },p);
 await page.clock.install({time:new Date('2026-10-08T10:00:00')});
 await page.goto(process.env.EQC_PREVIEW_URL||'http://127.0.0.1:5173');await page.locator('.workspace-sources .doc-row').first().click();
 await page.clock.pauseAt(new Date(await page.evaluate(()=>Date.now()+1000)));

 async function select(phrase){await page.evaluate(phrase=>{const root=document.querySelector('.doc-editor'),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const at=n.data.indexOf(phrase);if(at<0)continue;const r=document.createRange();r.setStart(n,at);r.setEnd(n,at+phrase.length);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(r);document.dispatchEvent(new Event('selectionchange'));return;}throw Error('Phrase not found');},phrase);await page.getByText('Selection actions',{exact:true}).waitFor();}

 await page.getByTitle('Profile & time',{exact:true}).click();await page.getByRole('heading',{name:'Profile & time'}).waitFor();assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),'0:00:00');
 await page.getByRole('button',{name:'Back to Workspace'}).click();await select('Bob discusses');await page.locator('.workspace-grid .right-panel .code-name').getByText('Cost',{exact:true}).click();await page.waitForFunction(()=>window.__qaProject.codedSegments.length===2);
 await page.clock.runFor(60000);await page.getByTitle('Profile & time',{exact:true}).click();assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),'0:01:00');
 await page.getByRole('heading',{name:'My details',exact:true}).waitFor();await page.getByLabel('Name',{exact:true}).fill('Amina');await page.getByLabel('Email',{exact:true}).fill('amina@example.test');await page.getByLabel('Role / designation',{exact:true}).fill('Researcher');
 const details=await page.evaluate(()=>(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).details;})());assert.equal(details.name,'Amina');assert.equal(details.email,'amina@example.test');await page.clock.runFor(501);assert.equal(await page.evaluate(()=>window.__qaProject.coderName),'Amina');assert.equal(await page.evaluate(()=>window.__qaProject.codedSegments[0].coder),'Ann');
 assert.equal(await page.locator('.profile-reward').count(),0);assert.equal(await page.getByText('Daily goal & little rewards',{exact:true}).count(),0);

 await page.getByTitle('Rename project',{exact:true}).click();const coderInput=page.locator('.modal-input[placeholder="e.g. Anisur, RA-2"]');await coderInput.fill('Ravi');await page.getByRole('button',{name:'Save',exact:true}).click();await page.clock.runFor(501);assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Ravi');
 await page.getByRole('button',{name:'🌐 LAN',exact:true}).click();const hostName=page.getByPlaceholder('e.g. Anisur (Coder 1)');await hostName.waitFor();assert.equal(await hostName.inputValue(),'Ravi');await hostName.fill('Leena');await hostName.press('Tab');await page.clock.runFor(501);await page.getByRole('button',{name:'✕',exact:true}).click();assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Leena');assert.equal(await page.evaluate(()=>window.__qaProject.coderName),'Leena');assert.equal(await page.evaluate(()=>(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).details;})().name),'Leena');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export time CSV'}).click();assert.ok((await download).suggestedFilename().endsWith('.csv'));
 await page.getByRole('button',{name:'Pause tracking'}).click();await page.getByRole('button',{name:'Resume tracking'}).waitFor();const expectedCoding=await page.locator('.profile-totals > div').first().locator('strong').textContent();const before=await page.evaluate(()=>(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).records;})().reduce((sum,r)=>sum+r.appMs,0));await page.clock.runFor(30000);assert.equal(await page.evaluate(()=>(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).records;})().reduce((sum,r)=>sum+r.appMs,0)),before);await page.getByRole('button',{name:'Resume tracking'}).click();
 for(const period of ['week','month','year','day']){await page.getByLabel('Period',{exact:true}).selectOption(period);assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),expectedCoding);}

 const originalId=await page.getByLabel('Active profile',{exact:true}).inputValue();const originalTime=await page.locator('.profile-totals > div').first().locator('strong').textContent();
 const avatar=page.getByTitle('Profile & time',{exact:true});assert.equal(await avatar.evaluate(el=>getComputedStyle(el).borderRadius),'50%');const avatarBox=await avatar.boundingBox();assert.equal(avatarBox.width,32);assert.equal(avatarBox.height,32);
 await page.getByLabel('Profile picture',{exact:true}).setInputFiles('release/profile-qa/avatar.png');await page.locator('.profile-avatar-button img').waitFor();const portrait=await page.locator('.profile-portrait').boundingBox(),detailsBox=await page.locator('.profile-details').boundingBox();assert.equal(portrait.width,150);assert.ok(Math.abs((portrait.x+portrait.width/2)-(detailsBox.x+detailsBox.width/2))<2);
 await page.getByRole('button',{name:'New profile',exact:true}).click();const secondId=await page.getByLabel('Active profile',{exact:true}).inputValue();assert.notEqual(secondId,originalId);await page.getByLabel('Name',{exact:true}).fill('Samira');await page.clock.runFor(501);assert.equal(await page.evaluate(()=>window.__qaProject.coderName),'Samira');assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),'0:00:00');
 await page.getByLabel('Active profile',{exact:true}).selectOption(originalId);await page.clock.runFor(501);assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Leena');assert.equal(await page.evaluate(()=>window.__qaProject.coderName),'Leena');assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),originalTime);
 await page.getByLabel('Active profile',{exact:true}).selectOption(secondId);await page.getByRole('button',{name:'Delete profile…',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('select[aria-label="Active profile"] option').count(),2);await page.getByRole('button',{name:'Delete profile…',exact:true}).click();await page.getByRole('button',{name:'Delete profile',exact:true}).click();assert.equal(await page.locator('select[aria-label="Active profile"] option').count(),1);assert.equal(await page.getByLabel('Active profile',{exact:true}).inputValue(),originalId);
 // JSON includes only selected profile; repeated imports preserve later work without duplicate session IDs.
 await page.getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬇️ Export',exact:true}).click();await page.getByRole('button',{name:'Export project',exact:true}).click();const backup=await page.evaluate(()=>window.__exports.at(-1)[0]);assert.equal(backup.researchProfile.profile.id,originalId);assert.ok(backup.researchProfile.profile.records.length>0);assert.ok(backup.researchProfile.profile.lastWorkedAt>0);assert.ok(backup.researchProfile.profile.details.photo);
 const codingBefore=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).records.reduce((sum,r)=>sum+r.codingMs,0);});
 for(let i=0;i<2;i++){await page.evaluate(p=>window.__nextImport=p,backup);await page.getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬆️ Import',exact:true}).click();await page.getByTitle('Profile & time',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('.profile-panel'));assert.equal(await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));const p=s.profiles.find(p=>p.id===s.activeId);return p.records.reduce((sum,r)=>sum+r.codingMs,0);}),codingBefore);assert.equal(await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));const p=s.profiles.find(p=>p.id===s.activeId);return new Set(p.records.map(r=>r.id)).size===p.records.length;}),true);}
 const other=structuredClone(backup);other.researchProfile.profile.id='new-profile-from-another-computer';other.researchProfile.profile.details.name='Imported researcher';await page.evaluate(p=>window.__nextImport=p,other);await page.getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬆️ Import',exact:true}).click();await page.getByTitle('Profile & time',{exact:true}).click();assert.equal(await page.locator('select[aria-label="Active profile"] option').count(),2);assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Imported researcher');await page.getByLabel('Active profile',{exact:true}).selectOption(originalId);await page.clock.runFor(501);
 fs.mkdirSync('release/profile-qa',{recursive:true});await page.screenshot({path:'release/profile-qa/Profile.png'});
 for(const width of [1024,800,640]){await page.setViewportSize({width,height:768});assert.equal(await page.locator('.app-shell').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:`release/profile-qa/Profile-${width}.png`});}
 await page.reload();await page.clock.runFor(3500);await page.getByTitle('Profile & time',{exact:true}).click();await page.getByRole('heading',{name:'My details',exact:true}).waitFor();assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Leena');assert.equal(await page.locator('.profile-totals > div').first().locator('strong').textContent(),expectedCoding);
 for(const [minutes,asset] of [[30,'Charmander'],[60,'Eevee']]) {
   await page.evaluate(minutes=>localStorage.setItem('eqc-qa-earned-minutes',String(minutes)),minutes);
   await page.reload();await page.clock.runFor(3500);await page.getByTitle('Profile & time',{exact:true}).click();await page.getByRole('dialog',{name:minutes===30?'A little spark':'An hour of possibilities'}).waitFor();assert.ok(await page.getByRole('img',{name:asset+' illustration',exact:true}).count()>0);await page.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.getByText('Daily goal & little rewards',{exact:true}).count(),0);
 }
const timeBeforeCheat=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).records.reduce((n,r)=>n+r.codingMs,0);});await page.getByLabel('Role / designation',{exact:true}).fill('pikachu');await page.waitForFunction(()=>document.querySelectorAll('.milestone-badge').length===15);assert.equal(await page.getByLabel('Role / designation',{exact:true}).inputValue(),'Researcher');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('eqc-profiles-v2'));return s.profiles.find(p=>p.id===s.activeId).records.reduce((n,r)=>n+r.codingMs,0);}),timeBeforeCheat);
assert.deepEqual(errors,[]);
 console.log('Profile: actual coding, local persistence, optional details, daily/weekly/monthly/yearly totals, hidden/earned rewards, CSV, shared identities, multi-profile switching/deletion, avatar/photo, JSON time deduplication and responsive layout passed.');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1);});
