const test=require('node:test'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
const {createProfileTimeStore}=require('../electron/profileTimeStore.cjs');
function database(){const native=new DatabaseSync(':memory:');native.exec('PRAGMA foreign_keys=ON');const db={exec:sql=>native.exec(sql),prepare(sql){const s=native.prepare(sql);s.setAllowUnknownNamedParameters(true);return s;},transaction(fn){return(...args)=>{native.exec('BEGIN');try{const result=fn(...args);native.exec('COMMIT');return result;}catch(e){native.exec('ROLLBACK');throw e;}};}};return {native,db};}
const record=(id='s',ms=30000,day='2026-10-08',projectId='p')=>({id,day,projectId,projectName:'Study',start:100,end:100+ms,appMs:ms,codingMs:ms,firstCoding:100,lastCoding:200});
const profile=(id='person')=>({id,details:{name:'Amina',email:'a@example.test',designation:'RA',organization:'',photo:'',paused:false,workspaceAnimations:true},records:[record()],updatedAt:100,lastWorkedAt:30100,milestones:[]});
function setup(legacy){const d=database(),store=createProfileTimeStore(d.db);store.open(legacy||{version:2,activeId:'person',profiles:[profile()]});return {...d,store};}
test('transactional migration is verified, idempotent and preserves identity/details/time',()=>{const {native,store}=setup();try{const backup=store.backup('person');assert.equal(backup.profile.records[0].codingMs,30000);assert.equal(backup.profile.details.workspaceAnimations,true);store.open({version:2,activeId:'person',profiles:[{...profile(),records:[record('s',10000)]}]});assert.equal(store.backup('person').profile.records[0].codingMs,30000);assert.equal(store.needsMigration(),false);assert.equal(store.open().rows[0].codingMs,30000);}finally{native.close();}});
test('incremental writes, older/repeated backups and day rollups never duplicate or shrink time',()=>{const {native,store}=setup();try{store.write({profileId:'person',records:[record('s',60000),record('s2',10000)]});assert.equal(store.open().rows[0].codingMs,70000);const b=store.backup('person');store.import(b);store.import(b);store.import({version:1,profile:profile()});assert.equal(store.open().rows[0].codingMs,70000);assert.equal(store.backup('person').profile.records.length,2);assert.equal(store.open().profile.lastWorkedAt,60100);}finally{native.close();}});
test('metadata updates preserve separately stored photos and cheat unlock never changes recorded time',()=>{const p=profile();p.details.photo='data:image/png;base64,AAAA';const {native,store}=setup({version:2,activeId:p.id,profiles:[p]});try{const {photo,...metadata}=p.details;store.write({profileId:p.id,records:[],details:{...metadata,designation:'Investigator'},updatedAt:101});assert.equal(store.open().profile.details.photo,photo);assert.equal(store.open().profile.details.designation,'Investigator');assert.equal(JSON.parse(native.prepare('SELECT details FROM research_profiles WHERE id=?').get(p.id).details).photo,undefined);const before=store.backup(p.id).profile.records;store.write({profileId:p.id,records:[],unlockAll:true});assert.equal(store.open().profile.milestones.length,15);assert.ok(store.open().profile.milestones.every(a=>a.seenAt));assert.deepEqual(store.backup(p.id).profile.records,before);store.write({profileId:p.id,records:[],details:{...metadata,photo:''},updatedAt:102});assert.equal(store.open().profile.details.photo,'');}finally{native.close();}});
test('a failed batch or migration leaves records, rollups and metadata unchanged',()=>{const {native,store}=setup();try{assert.throws(()=>store.write({profileId:'person',details:{...profile().details,name:'Wrong'},updatedAt:999,records:[record('new'),{...record('s'),projectId:'conflict'}]}),/conflicting/);assert.equal(store.open().profile.details.name,'Amina');assert.equal(store.backup('person').profile.records.length,1);assert.equal(store.open().rows[0].codingMs,30000);}finally{native.close();}
 const d=database(),s=createProfileTimeStore(d.db);try{assert.throws(()=>s.open({version:2,activeId:'person',profiles:[profile(),{...profile('bad'),records:[{...record(),codingMs:-1}]}]}),/Invalid/);assert.equal(d.db.prepare('SELECT COUNT(*) AS n FROM research_profiles').get().n,0);assert.equal(s.needsMigration(),true);}finally{d.native.close();}});
test('milestones/seen states persist independently of metadata precedence and profile deletion cascades',()=>{const {native,store}=setup();try{store.write({profileId:'person',records:[record('s',30*60000)]});assert.ok(store.open().profile.milestones.some(a=>a.id==='time-30'));store.write({profileId:'person',records:[],seenId:'time-30'});const seen=store.open().profile.milestones[0].seenAt;assert.ok(seen);const old=profile();old.milestones=[{id:'time-30',earnedAt:10}];store.import({version:1,profile:old});assert.equal(store.open().profile.milestones[0].seenAt,seen);
 const next=store.create();assert.equal(next.profile.details.workspaceAnimations,false);assert.equal(next.rows.length,0);assert.equal(next.profile.milestones.length,0);store.select('person');store.delete('person');assert.equal(native.prepare('SELECT COUNT(*) AS n FROM research_time_sessions WHERE profile_id=?').get('person').n,0);assert.equal(native.prepare('SELECT COUNT(*) AS n FROM research_time_days WHERE profile_id=?').get('person').n,0);assert.equal(store.open().profile.id,next.profile.id);}finally{native.close();}});
test('SQL eligibility matches cumulative time, Sunday weeks, completed years and distinct project rules',()=>{const p=profile();p.records=Array.from({length:50},(_,i)=>record('project'+i,i?60000:480*60000,'2026-01-01','p'+i));for(const day of [...Array.from({length:12},(_,i)=>`2025-${String(i+1).padStart(2,'0')}-15`),'2025-09-01','2025-09-07','2025-09-14','2025-09-21','2025-09-28','2025-10-01','2025-10-02','2025-10-03','2025-10-04','2025-10-05'])p.records.push(record(day,60000,day));const {native,store}=setup({version:2,activeId:p.id,profiles:[p]});try{assert.equal(store.open().profile.milestones.length,12);assert.equal(store.open().profile.milestones.filter(a=>a.seenAt).length,0);}finally{native.close();}});
test('large history stays in SQL: startup/switch returns aggregates, only backup reads sessions',()=>{const p=profile();p.records=Array.from({length:10000},(_,i)=>record('session-'+i,1000,'2026-10-08','p'+i%3));const began=performance.now(),{native,store}=setup({version:2,activeId:p.id,profiles:[p]});try{const snapshot=store.open();assert.equal(snapshot.rows.length,3);assert.equal(snapshot.profile.records,undefined);assert.equal(snapshot.rows.reduce((n,r)=>n+r.codingMs,0),10000000);store.write({profileId:p.id,records:[record('session-0',2000,'2026-10-08','p0')]});assert.equal(store.open().rows.reduce((n,r)=>n+r.codingMs,0),10001000);console.log(`10,000-session migration + incremental checks: ${Math.round(performance.now()-began)} ms; renderer receives 3 daily rows.`);}finally{native.close();}});
