const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), ts = require('typescript');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText, f);
const { projectForExport } = require('../src/lib/projectExport.ts');
const { mergeMemos, memoExportRows, listMemoRecords, updateMemoText } = require('../src/lib/memoTools.ts');
const { collectIcrCoders, scopedCoderCounts, buildCodingUnits } = require('../src/lib/icr.ts');
const { buildQdpxExport } = require('../src/lib/qdpxExport.ts');
const { readExchangeFile } = require('../electron/projectExchange.cjs');
const path = require('node:path'), JSZip = require('jszip');
function fixture() { return { id:'p', name:'Project', createdAt:1, folders:[], docs:[{ id:'d', name:'Transcript', content:'water', original:{name:'Transcript.docx',format:'docx',base64:'AA==',textHash:'retained'} }], codes:[{id:'c',name:'Water',parentId:null,color:'#f00'}], codedSegments:[{id:'s',docId:'d',codeId:'c',start:0,end:5,text:'water'}], images:[], codedRegions:[], memos:[{id:'m',title:'Finding',text:'First reflection',kind:'analytic',docIds:['d'],codeIds:['c'],caseIds:[],segmentIds:[],createdAt:1,updatedAt:1},{id:'n',title:'Method',text:'Second reflection',kind:'methodological',docIds:['d'],codeIds:[],caseIds:[],segmentIds:['s'],createdAt:2,updatedAt:2}] }; }
test('smaller export omits original bytes without mutating sources, coding or memo records', async () => { const p=fixture(), before=JSON.stringify(p); assert.equal(projectForExport(p,true),p);const data=projectForExport(p,false);assert.equal(data.docs[0].original,undefined);assert.equal(data.codedSegments,p.codedSegments);assert.equal(data.memos,p.memos);assert.equal(JSON.stringify(p),before);const payload=await buildQdpxExport(data);assert.ok(!payload.qdeXml.includes('richTextPath'));assert.ok(payload.qdeXml.includes('PlainTextSelection')); });
test('memo merge retains destination identity, all texts, original dates and deduplicated links', () => { const p=fixture(), before=JSON.stringify(p), next=mergeMemos(p,['m','n'],'m');assert.equal(next.memos.length,1);assert.equal(next.memos[0].id,'m');assert.equal(next.memos[0].kind,'analytic');assert.equal(next.memos[0].createdAt,1);assert.equal(next.memos[0].text,'First reflection\n\nMethod\nSecond reflection');assert.deepEqual(next.memos[0].docIds,['d']);assert.deepEqual(next.memos[0].segmentIds,['s']);assert.equal(JSON.stringify(p),before);assert.throws(()=>mergeMemos(p,['m'],'m'));assert.throws(()=>mergeMemos(p,['m','n'],'missing')); });
test('single and selected memo exports retain human-readable linked source names and quotations', () => { const p=fixture();const rows=memoExportRows(p,['n']);assert.equal(rows.length,1);assert.equal(rows[0].Documents,'Transcript');assert.equal(rows[0].Excerpts,'Transcript: water');assert.equal(rows[0].Memo,'Second reflection');assert.equal(memoExportRows(p,['m','n']).length,2); });
test('attached code/source memos can be selected, exported, edited and merged without changing coding', () => {
  const p=fixture();p.codes[0].summary='Code interpretation';p.codes[0].definition='Coding rule';p.docs[0].notes='Source context';const before=JSON.stringify(p),records=listMemoRecords(p),code=records.find(m=>m.origin.kind==='code'),doc=records.find(m=>m.origin.kind==='document');
  assert.equal(memoExportRows(p,[code.id,doc.id]).length,2);assert.equal(updateMemoText(p,code,'Revised').codes[0].summary,'Revised');const next=mergeMemos(p,[code.id,doc.id],'new','Combined findings');const merged=next.memos.find(m=>m.title==='Combined findings');assert.ok(merged.text.includes('Code interpretation'));assert.ok(merged.text.includes('Source context'));assert.deepEqual(merged.codeIds,['c']);assert.deepEqual(merged.docIds,['d']);assert.equal(next.codes[0].summary,'');assert.equal(next.codes[0].definition,'Coding rule');assert.equal(next.docs[0].notes,'');assert.equal(next.docs[0].content,'water');assert.deepEqual(next.codedSegments,p.codedSegments);assert.equal(JSON.stringify(p),before);
});
test('62 text assignments plus 6 regions remain distinct from 30 overlapping passage groups', () => {
  const p=fixture();p.docs[0].content='x'.repeat(600);p.codedSegments=Array.from({length:30},(_,i)=>({id:'base'+i,docId:'d',codeId:'c',start:i*20,end:i*20+10,text:'x'.repeat(10),coder:'SK'}));for(let i=0;i<32;i++)p.codedSegments.push({...p.codedSegments[i%30],id:'extra'+i});for(let i=0;i<2;i++)p.codedSegments.push({...p.codedSegments[0],id:'other'+i,coder:'B'});p.codedRegions=Array.from({length:6},(_,i)=>({id:'r'+i,imageId:'image',codeId:'c',coder:'SK',x:0,y:0,width:1,height:1}));
  assert.equal(collectIcrCoders(p).attributed.find(c=>c.name==='SK').segments,62);assert.deepEqual(scopedCoderCounts(p,'SK',['d'],true),{name:'SK',segments:62,regions:6});assert.equal(scopedCoderCounts(p,'SK',[],false).segments,0);const groups=buildCodingUnits(p,['SK','B'],['d']);assert.equal(groups.length,30);assert.equal(groups.filter(g=>g.distinctCoders>=2).length,1);assert.equal(groups.reduce((n,g)=>n+g.segmentIds.length,0),64);
});
test('QDPX, QDC and extracted QDE preserve source files and report malformed archives', async () => {
  const directory=fs.mkdtempSync(path.join(__dirname,'exchange-qa-'));
  const root=path.resolve(__dirname); assert.ok(path.resolve(directory).startsWith(root+path.sep));
  try {
    const xml='<Project xmlns="urn:QDA-XML:project:1.0"/>', zip=new JSZip();zip.file('project.qde',xml);zip.file('Sources/transcript.txt','Bengali পানি');zip.file('Sources/original.docx',Buffer.from([1,2,3]));
    const archive=path.join(directory,'project.qdpx');fs.writeFileSync(archive,await zip.generateAsync({type:'nodebuffer'}));const packed=await readExchangeFile(archive);assert.equal(packed.qdeXml,xml);assert.equal(packed.sourceFiles['Sources/transcript.txt'],'Bengali পানি');assert.equal(packed.sourceBytes['Sources/original.docx'],'AQID');
    const qde=path.join(directory,'project.qde');fs.writeFileSync(qde,xml);fs.mkdirSync(path.join(directory,'Sources'));fs.writeFileSync(path.join(directory,'Sources/transcript.txt'),'Bengali পানি');assert.equal((await readExchangeFile(qde)).sourceFiles['Sources/transcript.txt'],'Bengali পানি');
    const qdc=path.join(directory,'codebook.qdc');fs.writeFileSync(qdc,'<CodeBook/>');assert.equal((await readExchangeFile(qdc)).qdeXml,'<CodeBook/>');
    const broken=path.join(directory,'broken.qdpx');fs.writeFileSync(broken,await new JSZip().generateAsync({type:'nodebuffer'}));await assert.rejects(readExchangeFile(broken),/No project.qde/);
  } finally { fs.rmSync(directory,{recursive:true,force:true}); }
});
