const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,f);
const R=require('../src/lib/research.ts'),{mergeCodes}=require('../src/lib/mergeCodes.ts'),{mergeProjectInto}=require('../src/lib/merge.ts'),{researchRows,researchHtml,retrievedReport}=require('../src/lib/researchExport.ts');
const history=require('../electron/projectHistory.cjs');
const {buildScopedExport}=require('../src/lib/exportBuilders.ts'),{buildCodeReport}=require('../src/lib/codeReport.ts');
const {DatabaseSync}=require('node:sqlite');
function fixture(){return {id:'p',name:'Research',createdAt:1,folders:[],docs:[{id:'d',name:'FGD',content:'Alice water costs. Bob drainage fails.',addedAt:1},{id:'e',name:'Interview',content:'Water costs.',addedAt:1}],codes:[{id:'a',name:'Water',parentId:null,color:'#f00',summary:''},{id:'b',name:'Cost',parentId:null,color:'#00f',summary:''}],codedSegments:[{id:'s',docId:'d',codeId:'a',start:6,end:11,text:'water',coder:'Ann',note:'memo',starred:true,createdAt:1},{id:'t',docId:'d',codeId:'b',start:9,end:17,text:'er costs',coder:'Ann',createdAt:1},{id:'u',docId:'d',codeId:'b',start:23,end:31,text:'drainage',coder:'Bob',createdAt:1},{id:'v',docId:'e',codeId:'a',start:0,end:5,text:'Water',coder:'Ann',createdAt:1}],images:[{id:'i',name:'Photo',dataUrl:'data:image/png;base64,AA==',addedAt:1}],codedRegions:[{id:'r',imageId:'i',codeId:'a',x:0,y:0,width:.5,height:.5,createdAt:1},{id:'q',imageId:'i',codeId:'b',x:.4,y:.4,width:.5,height:.5,createdAt:1}],cases:[{id:'alice',name:'Alice',kind:'person',attributes:{Age:'35',Location:'Town'},links:[{docId:'d',start:0,end:18}]},{id:'bob',name:'Bob',kind:'person',attributes:{Age:'20'},links:[{docId:'d',start:19,end:36}]}],groups:[{id:'g',name:'Interviews',kind:'documents',memberIds:['d']}],annotations:[{id:'n',docId:'d',start:6,end:11,text:'water',note:'Why?',createdAt:1}],memos:[{id:'m',title:'Finding',text:'Compare participants',kind:'analytic',docIds:['d'],codeIds:['b'],caseIds:['alice'],segmentIds:['t'],createdAt:1,updatedAt:1}],queries:[{...R.emptyQuery(),id:'query',name:'Costs',codeIds:['b'],caseIds:['alice'],documentGroupIds:['g']}]};}
const run=(p,q)=>R.retrieveExcerpts(p,{...R.emptyQuery(),...q}).map(r=>r.id).sort();
test('query scope, boolean conditions and FGD speakers remain separate',()=>{const p=fixture();assert.deepEqual(run(p,{codeIds:['a','b'],operator:'all',caseIds:['alice']}),['s','t']);assert.deepEqual(run(p,{codeIds:['a','b'],operator:'all',caseIds:['bob']}),[]);assert.deepEqual(run(p,{codeIds:['a'],operator:'without',excludeCodeIds:['b'],coder:'Ann'}),['v']);assert.deepEqual(run(p,{codeIds:['a','b'],operator:'overlap',docIds:['d']}),['s','t']);assert.deepEqual(run(p,{codeIds:['a','b'],operator:'overlap',docIds:['i']}),['q','r']);assert.deepEqual(run(p,{codeIds:['a','b'],operator:'near',distance:12,docIds:['d']}),['s','t','u']);assert.deepEqual(run(p,{attribute:{name:'Age',operator:'gt',value:'30'}}),['s','t']);assert.deepEqual(run(p,{codeGroupIds:['deleted']}),[]);assert.deepEqual(run(p,{documentGroupIds:['deleted']}),[]);assert.deepEqual(run(p,{caseIds:['deleted']}),[]);assert.deepEqual(run(p,{documentGroupIds:['g'],starredOnly:true}),['s']);});
test('reassignment, splitting and resizing preserve coding identity and memo metadata',()=>{const p=fixture();const changed=R.resizeExcerpt(p,'s',0,11);assert.equal(changed.codedSegments[0].text,'Alice water');assert.equal(changed.codedSegments[0].note,'memo');assert.equal(p.codedSegments[0].start,6);assert.throws(()=>R.resizeExcerpt(p,'s',-1,3));const split=R.splitCode(p,'a',['s','r'],'Water access');assert.equal(split.codes.length,3);assert.equal(split.codedSegments[0].codeId,split.codes[2].id);assert.equal(split.codedRegions[0].codeId,split.codes[2].id);assert.equal(split.codedSegments[0].coder,'Ann');assert.throws(()=>R.splitCode(p,'a',['u'],'Bad selection'));});
test('child coding satisfies its parent query branch without requiring every sibling',()=>{const p=fixture();p.codes.push({id:'parent',name:'Infrastructure',parentId:null,color:'#000',summary:''},{id:'unused',name:'Unused sibling',parentId:'parent',color:'#000',summary:''});p.codes[0].parentId='parent';assert.deepEqual(run(p,{codeIds:['parent','b'],operator:'all',descendants:true,docIds:['d']}),['s','t','u']);assert.deepEqual(run(p,{codeIds:['parent','b'],operator:'overlap',descendants:true,docIds:['d']}),['s','t']);assert.deepEqual(run(p,{codeIds:['parent','b'],operator:'all',descendants:false,docIds:['d']}),[]);});
test('merging codes and projects remaps all research references and is repeatable',()=>{const p=fixture(),merged=mergeCodes(p,['a','b'],'a');assert.deepEqual(merged.memos[0].codeIds,['a']);assert.deepEqual(merged.queries[0].codeIds,['a']);const target={id:'other',name:'Other',createdAt:2,folders:[],docs:[],codes:[],codedSegments:[]};mergeProjectInto(target,p);assert.equal(target.cases.length,2);assert.equal(target.memos.length,1);assert.ok(target.memos[0].segmentIds.every(id=>target.codedSegments.some(s=>s.id===id)));assert.ok(target.queries[0].documentGroupIds.every(id=>target.groups.some(g=>g.id===id)));mergeProjectInto(target,p);assert.equal(target.cases.length,2);assert.equal(target.memos.length,1);assert.equal(target.annotations.length,1);assert.equal(target.queries.length,1);assert.equal(target.codedSegments.length,4);});
test('editing source text relocates annotations and participant links or preserves unlinked notes',()=>{const p=fixture();const next=R.relocateResearchAfterEdit(p,'d','Intro. '+p.docs[0].content);assert.equal(next.annotations[0].start,13);assert.equal(next.cases[0].links[0].start,7);const lost=R.relocateResearchAfterEdit(p,'d','Completely different source');assert.equal(lost.annotations.length,0);assert.ok(lost.memos.some(m=>m.text.includes('Why?')));assert.ok(lost.memos.some(m=>m.title.includes('Unlinked case passage')));});
test('research reports escape content and retrieve only chosen coding',()=>{const p=fixture();p.memos[0].text='<script>bad</script>';assert.ok(researchHtml(p).includes('&lt;script&gt;'));assert.ok(researchRows(p).some(r=>r[0]==='Annotation'));const report=retrievedReport(p,R.retrieveExcerpts(p,{...R.emptyQuery(),docIds:['e']}),'Interview findings');assert.equal(report.sources.length,1);assert.equal(report.sources[0].name,'Interview');});
test('coding CSV and narrative Word include case attributes, annotations and linked memos',()=>{const p=fixture(),csv=buildScopedExport(p,'codesExcerptsSummaries');assert.ok(csv.headers.includes('Cases'));assert.ok(csv.csv.includes('Age=35'));assert.ok(csv.csv.includes('Annotation: Why?'));assert.ok(csv.csv.includes('Compare participants'));const report=buildCodeReport(p,'codesExcerptsSummaries');const source=report.sources.find(s=>s.name==='FGD');assert.ok(source.memo.includes('Finding'));const excerpt=source.codes.find(c=>c.id==='a').excerpts[0];assert.equal(excerpt.cases,'Alice');assert.ok(excerpt.attributes.includes('Age=35'));assert.ok(excerpt.note.includes('Why?'));});
test('SQLite activity and recovery survive reopening, rotate automatic points and protect named checkpoints',()=>{const file='release/research-history-test.sqlite';try{fs.unlinkSync(file);}catch{}let db=new DatabaseSync(file);history.installHistory(db);let p=fixture();history.recordSave(db,null,p,{actor:'Ann'},1);for(let n=0;n<14;n++){const next={...p,name:'Version '+n};history.recordSave(db,p,next,{actor:'Ann'},(n+1)*600001);p=next;}history.snapshot(db,p,'Keep this checkpoint');const keep=history.readHistory(db,'p').snapshots.find(s=>!s.automatic);db.close();db=new DatabaseSync(file);const data=history.readHistory(db,'p');assert.equal(data.snapshots.filter(s=>s.automatic).length,10);assert.equal(data.activity.length,15);assert.deepEqual(history.readSnapshot(db,'p',keep.id),p);assert.throws(()=>history.readSnapshot(db,'wrong-project',keep.id));db.prepare('UPDATE project_snapshots SET data=? WHERE id=?').run('{}',keep.id);assert.throws(()=>history.readSnapshot(db,'p',keep.id),/integrity/);db.close();fs.unlinkSync(file);});
