const {chromium}=require(process.env.EQC_PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('pageerror',e=>errors.push(e.message));
 const p={id:'research',name:'Research QA',createdAt:1,folders:[],docs:[{id:'d',name:'FGD',content:'Alice discusses water costs.\nBob discusses drainage failures.',addedAt:1,folderId:null}],codes:[{id:'a',name:'Water',parentId:null,color:'#2563eb',summary:'Water memo',createdAt:1},{id:'b',name:'Cost',parentId:null,color:'#ea580c',summary:'',createdAt:1}],codedSegments:[{id:'s',docId:'d',codeId:'a',start:16,end:21,text:'water',coder:'Ann',note:'Check affordability',createdAt:1}],images:[],codedRegions:[]};
 await page.addInitScript(p=>{
  localStorage.setItem('qda-document-view','text');window.__qaProject=p;window.__exports=[];window.__checkpoints=[];
  const record=async(...args)=>{window.__exports.push(args);return 'synthetic-export';};
  window.qv=new Proxy({listProjects:async()=>[{id:p.id,name:p.name}],loadProject:async()=>window.__qaProject,saveProject:async p=>{window.__qaProject=structuredClone(p);return p;},exportText:record,exportDocxTable:record,
   projectHistory:async()=>({activity:[{id:1,at:1,actor:'Ann',summary:'1 text coding added'}],snapshots:window.__checkpoints.map(s=>({id:s.id,at:1,label:s.label,automatic:false,sizeBytes:2000}))}),
   createCheckpoint:async(_,label)=>{window.__checkpoints.push({id:window.__checkpoints.length+1,label,data:structuredClone(window.__qaProject)});return window.qv.projectHistory();},readSnapshot:async(_,id)=>window.__checkpoints.find(s=>s.id===id).data,
   lan:new Proxy({},{get:(_,n)=>String(n).startsWith('on')?()=>{}:async()=>({ok:true})})},{get:(t,n)=>t[n]||(String(n).startsWith('on')?()=>{}:async()=>null)});
 },p);
 await page.goto(process.env.EQC_PREVIEW_URL||'http://127.0.0.1:5173');await page.locator('.workspace-sources .doc-row').first().click();
 async function select(phrase){await page.evaluate(phrase=>{const root=document.querySelector('.doc-editor'),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const at=n.data.indexOf(phrase);if(at<0)continue;const r=document.createRange();r.setStart(n,at);r.setEnd(n,at+phrase.length);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(r);document.dispatchEvent(new Event('selectionchange'));return;}throw Error('Phrase not found');},phrase);await page.getByText('Selection actions',{exact:true}).waitFor();}
 async function open(){await page.locator('.workspace-sources').getByText('Research tools',{exact:true}).click();await page.getByRole('button',{name:'Cases & attributes',exact:true}).click();await page.getByRole('dialog',{name:'Research tools'}).waitFor();}
 const modal=page.locator('.research-workspace');
 await select('Alice discusses');await open();await modal.getByRole('button',{name:'New case',exact:true}).click();await modal.getByLabel('Name',{exact:true}).fill('Alice');await modal.getByLabel('Case attributes').fill('Age=35\nLocation=Town');await modal.getByRole('button',{name:'Link selected passage to this case'}).click();await modal.getByRole('button',{name:'Save case',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.cases?.length===1);assert.equal(await page.evaluate(()=>window.__qaProject.cases[0].links[0].end),15);
 await modal.getByRole('tab',{name:'Groups',exact:true}).click();await modal.getByRole('button',{name:'New group',exact:true}).click();await modal.getByLabel('Name',{exact:true}).fill('Interviews');await modal.getByText('Group members',{exact:false}).first().click();await modal.getByLabel('FGD',{exact:true}).check();await modal.getByRole('button',{name:'Save group',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.groups?.length===1);
 await modal.getByRole('tab',{name:'Review',exact:true}).click();await modal.getByLabel('Query name').fill('All coding');await modal.getByRole('button',{name:'Save query',exact:true}).click();await modal.getByRole('button',{name:'Run query',exact:true}).click();await modal.locator('.research-result').waitFor();await modal.getByRole('button',{name:'Export results CSV'}).click();await modal.getByRole('button',{name:'Export results Word'}).click();assert.equal(await page.evaluate(()=>window.__exports.length),2);
 await modal.getByText('Refine selected coding',{exact:false}).click();await modal.getByRole('checkbox',{name:'Select excerpt s',exact:true}).check();await modal.getByLabel('Split code name').fill('Access');await modal.getByRole('button',{name:'Split into new code'}).click({timeout:15000,noWaitAfter:true});await page.waitForFunction(()=>window.__qaProject.codes.length===3);
 await modal.getByRole('tab',{name:'Memos/Notes',exact:true}).click();await modal.getByRole('button',{name:'New memo',exact:true}).click();await modal.getByLabel('Title',{exact:true}).fill('Analytic reflection');await modal.getByLabel('Memo',{exact:true}).fill('Compare access and affordability.');await modal.getByRole('button',{name:'Save memo',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.memos?.length===1);
 await modal.getByRole('tab',{name:'History',exact:true}).click();await modal.getByLabel('Checkpoint label').fill('Before recoding');await modal.getByRole('button',{name:'Create checkpoint'}).click();await modal.getByText('Recovery point saved.',{exact:true}).waitFor();await modal.getByRole('button',{name:'Restore…',exact:true}).click();await modal.getByRole('button',{name:'Restore project',exact:true}).click();await modal.getByText('Recovery point restored.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__checkpoints.length),2);
 await modal.getByRole('button',{name:'Close research tools'}).click();await select('drainage');await page.getByText('Selection actions',{exact:true}).click();await page.getByRole('button',{name:'Add annotation',exact:true}).click();await page.locator('.modal input').fill('Clarify drainage causes.');await page.getByRole('button',{name:'Save annotation',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.annotations?.length===1);await page.locator('.passage-annotation').waitFor();
 await select('Bob discusses');await page.getByText('Selection actions',{exact:true}).click();await page.getByRole('button',{name:'Create in-vivo code'}).click();assert.equal(await page.locator('.modal input').inputValue(),'Bob discusses');await page.getByRole('button',{name:'Create and apply',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.codes.length===4);
 await select('failures.');await page.getByText('Selection actions',{exact:true}).click();await page.getByText('Apply multiple codes',{exact:true}).click();await page.locator('.selection-code-list').getByLabel('Water',{exact:true}).check();await page.locator('.selection-code-list').getByLabel('Cost',{exact:true}).check();await page.getByRole('button',{name:'Apply selected codes'}).click();await page.waitForFunction(()=>window.__qaProject.codedSegments.length===4);
 await page.getByText('Reading',{exact:true}).click();await page.getByLabel('Coding stripes',{exact:true}).check();await page.locator('.coding-margin button').first().waitFor();assert.ok(await page.locator('.coding-margin button').count()>=3);await page.getByText('Reading',{exact:true}).click();
 await open();await modal.getByRole('tab',{name:'Review',exact:true}).click();await modal.getByRole('button',{name:'Run query',exact:true}).click();await modal.getByRole('button',{name:'Adjust passage'}).first().click();await select('Alice');await page.getByText('Selection actions',{exact:true}).click();await page.getByRole('button',{name:'Update passage',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.codedSegments.some(s=>s.start===0&&s.end===5));
 await open();fs.mkdirSync('release/research-qa',{recursive:true});for(const size of [{width:1366,height:900},{width:1024,height:768},{width:800,height:600},{width:640,height:480}]){await page.setViewportSize(size);for(const tab of ['Cases','Groups','Review','Notes','History']){await modal.getByRole('tab',{name:tab,exact:true}).click();const bounds=await modal.boundingBox();assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=size.width+1&&bounds.y+bounds.height<=size.height+1);assert.equal(await modal.evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:path.resolve('release/research-qa/'+tab+'-'+size.width+'.png')});}}
 assert.deepEqual(errors,[]);
 const roundtrip=await page.evaluate(async()=>{const {buildQdpxExport}=await import('/src/lib/qdpxExport.ts'),{importQdpx}=await import('/src/lib/qdpxImport.ts'),{newProject}=await import('/src/domain.ts');const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;window.__qaProject.images=[{id:'photo',name:'Photo',dataUrl:canvas.toDataURL(),addedAt:1}];window.__qaProject.codedRegions=[{id:'area',imageId:'photo',codeId:'a',x:.123,y:.234,width:.456,height:.345,createdAt:1}];window.__qaProject.memos.push({id:'image-memo',title:'Image reflection',text:'Region-specific memo',kind:'analytic',docIds:['photo'],codeIds:[],caseIds:[],segmentIds:['area'],createdAt:1,updatedAt:1});const payload=await buildQdpxExport(window.__qaProject),imported=newProject('Roundtrip');await importQdpx(imported,payload);await importQdpx(imported,payload);return {payload,imported};});
 assert.equal(roundtrip.imported.cases.length,1);assert.equal(roundtrip.imported.groups.length,1);assert.equal(roundtrip.imported.memos.length,2);assert.equal(roundtrip.imported.memos.find(m=>m.title==='Image reflection').segmentIds[0],roundtrip.imported.codedRegions[0].id);assert.equal(roundtrip.imported.annotations.length,1);assert.equal(roundtrip.imported.queries.length,1);assert.ok(roundtrip.imported.cases[0].links.every(l=>roundtrip.imported.docs.some(d=>d.id===l.docId)));
 const validated=spawnSync(process.env.EQC_PYTHON||'python',[path.join(__dirname,'validate-qdpx.py')],{input:JSON.stringify(roundtrip.payload),encoding:'utf8'});assert.equal(validated.status,0,validated.stderr);
 console.log('Research tools: cases, groups, queries, review, exports, notes, checkpoints, annotations, in-vivo, multi-code, boundaries, stripes, four sizes and QDPX archive passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
