const {chromium}=require(process.env.EQC_PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:900},permissions:['clipboard-read','clipboard-write']}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const p={id:'p',name:'Export QA',createdAt:1,folders:[],docs:[{id:'d',name:'Transcript',folderId:null,notes:'Source reflection',content:'People discuss water access.',addedAt:1,original:{name:'Transcript.docx',format:'docx',base64:'AA==',textHash:'test'}}],codes:[{id:'c',name:'Water',parentId:null,color:'#2563eb',summary:'Attached code reflection',createdAt:1}],codedSegments:[{id:'s',docId:'d',codeId:'c',start:15,end:20,text:'water',createdAt:1}],images:[],codedRegions:[],memos:[{id:'m',title:'First finding',text:'First reflection',kind:'analytic',docIds:['d'],codeIds:['c'],caseIds:[],segmentIds:[],createdAt:1,updatedAt:1},{id:'n',title:'Second finding',text:'Second reflection',kind:'analytic',docIds:[],codeIds:[],caseIds:[],segmentIds:['s'],createdAt:1,updatedAt:1}]};localStorage.setItem('qda-document-view','text');window.__qaProject=p;window.__exports=[];window.qv=new Proxy({listProjects:async()=>[{id:p.id,name:p.name}],loadProject:async()=>window.__qaProject,saveProject:async p=>{window.__qaProject=p;return p;},lan:new Proxy({},{get:(_,n)=>String(n).startsWith('on')?()=>{}:async()=>({ok:true})})},{get:(t,n)=>t[n]||(String(n).startsWith('on')?()=>{}:async (...args)=>{window.__exports.push({name:n,args});return 'QA export';})});});
 await page.goto(process.env.EQC_PREVIEW_URL||'http://127.0.0.1:5173');await page.locator('.tabs button').last().waitFor();assert.deepEqual(await page.locator('.tabs button').allTextContents(),['Workspace','Codebook','Auto-Code','Analysis','Code Map','Help','About']);
 async function exportDialog(){await page.locator('.app-header').getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬇️ Export',exact:true}).click();return page.getByRole('dialog',{name:'Export project',exact:true});}
 let dialog=await exportDialog();await dialog.getByRole('button',{name:'Export project',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.ok(await page.evaluate(()=>window.__exports.find(e=>e.name==='exportBackup').args[0].docs[0].original));
 dialog=await exportDialog();await dialog.getByLabel('Export document contents').selectOption('text');await dialog.getByRole('button',{name:'Export project',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.__exports.filter(e=>e.name==='exportBackup').at(-1).args[0].docs[0].original),undefined);assert.ok(await page.evaluate(()=>window.__qaProject.docs[0].original));
 dialog=await exportDialog();await dialog.getByLabel('Project export format').selectOption('qdpx');await dialog.getByLabel('Export document contents').selectOption('text');await dialog.getByRole('button',{name:'Export project',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.ok(await page.evaluate(()=>window.__exports.find(e=>e.name==='exportQdpx').args[0].qdeXml.includes('PlainTextSelection')));
 await page.locator('.workspace-sources .doc-row').first().click();const toggle=page.getByRole('button',{name:'Codes & Strips',exact:true});await toggle.click();const stripe=page.locator('.coding-margin button').first();await stripe.waitFor();assert.equal(await stripe.locator('span').textContent(),'Water');await stripe.hover();await page.waitForTimeout(200);assert.equal(await stripe.evaluate(el=>getComputedStyle(el).borderLeftWidth),'7px');assert.equal(await page.evaluate(()=>localStorage.getItem('qda-coding-stripes')),'true');
 for(const appTheme of ['dark','light']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,appTheme);for(const reader of ['White','Paperwhite','Dark']){await page.locator('.workspace-grid .center-panel').getByRole('button',{name:reader,exact:false}).first().click();await stripe.hover();const colours=await stripe.evaluate(el=>({label:getComputedStyle(el.querySelector('span')).backgroundColor,viewer:getComputedStyle(el.closest('.center-panel')).backgroundColor,writing:getComputedStyle(el.querySelector('span')).writingMode}));assert.equal(colours.label,colours.viewer);assert.equal(colours.writing,'vertical-rl');}}await page.locator('.workspace-grid .center-panel').getByRole('button',{name:'White',exact:false}).first().click();
 await page.locator('.app-header').getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'Research tools',exact:true}).click();const modal=page.locator('.research-workspace');await modal.getByRole('tab',{name:'Review',exact:true}).click();assert.equal(await modal.getByLabel('Query operator').isVisible(),false);await modal.getByText('Advanced filters and combined queries',{exact:true}).click();await modal.getByLabel('Query operator').selectOption('overlap');await modal.getByRole('button',{name:'Run query',exact:true}).click();await modal.getByRole('tab',{name:'Notes',exact:true}).click();const first=modal.locator('.research-notes-list article').first();await first.getByRole('button',{name:'Copy memo text'}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'First reflection');await first.getByRole('button',{name:'Export memo Word'}).click();await first.getByRole('button',{name:'Export memo CSV'}).click();assert.ok(await page.evaluate(()=>window.__exports.some(e=>e.name==='exportText'&&e.args[0].content.includes('First reflection'))));
 await modal.getByText('Export or merge selected memos',{exact:false}).click();await modal.getByLabel('Select memo First finding').check();await modal.getByLabel('Select memo Second finding').check();await modal.getByLabel('Destination memo').selectOption('m');await modal.getByRole('button',{name:'Merge selected memos…'}).click();assert.equal(await page.evaluate(()=>window.__qaProject.memos.length),2);await modal.getByRole('button',{name:'Confirm memo merge'}).click();await page.waitForFunction(()=>window.__qaProject.memos.length===1);assert.ok(await page.evaluate(()=>window.__qaProject.memos[0].text.includes('Second reflection')));await modal.getByLabel('Select memo Code memo — Water').check();await modal.getByLabel('Select memo Source memo — Transcript').check();await modal.getByLabel('Destination memo').selectOption('new');await modal.getByLabel('Combined memo title').fill('Attached findings');await modal.getByRole('button',{name:'Selected memos CSV'}).click();await modal.getByRole('button',{name:'Merge selected memos…'}).click();await modal.getByRole('button',{name:'Confirm memo merge'}).click();await page.waitForFunction(()=>window.__qaProject.memos.some(m=>m.title==='Attached findings'));assert.equal(await page.evaluate(()=>window.__qaProject.codes[0].summary),'');assert.equal(await page.evaluate(()=>window.__qaProject.docs[0].content),'People discuss water access.');await modal.getByRole('button',{name:'Close research tools'}).click();
 await page.locator('.tabs').getByRole('button',{name:'Help',exact:true}).click();await page.getByLabel('Search documentation').fill('refinement');assert.ok(await page.locator('.help-sections details').count()>0);assert.ok(await page.locator('.help-sections').textContent().then(t=>t.includes('Adjust passage')));await page.getByLabel('Search documentation').fill('xyz-no-match');await page.getByText('No matching sections.',{exact:false}).waitFor();await page.getByLabel('Search documentation').fill('');
 fs.mkdirSync('release/usability-qa',{recursive:true});for(const width of [1366,1024,800,640]){await page.setViewportSize({width,height:width===640?480:768});for(const tab of ['Help','About']){await page.locator('.tabs').getByRole('button',{name:tab,exact:true}).click();assert.equal(await page.locator('.app-shell').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:`release/usability-qa/${tab}-${width}.png`});}}
 await page.locator('.tabs').getByRole('button',{name:'Help',exact:true}).click();await page.getByLabel('Search documentation').fill('About');const aboutHelp=page.locator('.help-sections details').filter({has:page.locator('summary',{hasText:'10. The About Tab'})});assert.ok(!(await aboutHelp.textContent()).includes('build metadata'));assert.equal(await aboutHelp.locator('li').count(),7);assert.equal(await page.locator('.help-text').filter({hasText:'screenshots/eQc_About'}).count(),0);await page.getByLabel('Search documentation').fill('');
 const exchange=await page.evaluate(()=>window.__exports.find(e=>e.name==='exportQdpx').args[0]);await page.evaluate(payload=>{window.qv.importBackup=async()=>({format:'refi',payload});},exchange);await page.locator('.app-header').getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬆️ Import',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.id!=='p');assert.equal(await page.evaluate(()=>window.__qaProject.docs.length),1);assert.equal(await page.evaluate(()=>window.__qaProject.codedSegments[0].text),'water');
 await page.evaluate(()=>{window.qv.importBackup=async()=>({format:'refi',payload:{fileName:'Book.qdc',qdeXml:'<CodeBook xmlns="urn:QDA-XML:codebook:1.0"><Codes><Code guid="abc" name="Imported code"/></Codes></CodeBook>',sourceFiles:{},sourceBytes:{}}});});await page.locator('.app-header').getByText('Project tools',{exact:true}).click();await page.getByRole('button',{name:'⬆️ Import',exact:true}).click();await page.waitForFunction(()=>window.__qaProject.name==='Book');assert.equal(await page.evaluate(()=>window.__qaProject.docs.length),0);assert.ok(await page.evaluate(()=>window.__qaProject.codes.some(c=>c.name==='Imported code')));
 assert.deepEqual(errors,[]);console.log('v1.7.0 usability: navigation, export formats/original choices, visible stripes/hover, progressive review, memo exports/merge and searchable Help across four sizes passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
