import React, { useEffect, useRef, useState } from 'react';
import { duration, inPeriod, localDay, LocalProfile, TimeRow } from '../lib/timeTracking';
import ProfileMilestones from './ProfileMilestones';
import { MilestoneAward } from '../lib/milestones';
export default function ProfilePanel({profile,setProfile,rows,status,error,onClose,profiles,profileId,selectProfile,addProfile,deleteProfile,milestones,markMilestoneSeen,busy,unlockMilestones}:{profile:LocalProfile;setProfile:(profile:LocalProfile)=>void;rows:TimeRow[];status:string;error:string;onClose:()=>void;profiles:Array<{id:string;name:string;email:string;lastWorkedAt:number}>;profileId:string;selectProfile:(id:string)=>void;addProfile:()=>void;deleteProfile:()=>void;milestones:MilestoneAward[];markMilestoneSeen:(id:string)=>void;busy:boolean;unlockMilestones:()=>void}) {
  const [period,setPeriod]=useState('day'),[date,setDate]=useState(localDay(Date.now())),[photoError,setPhotoError]=useState(''),[deleteConfirm,setDeleteConfirm]=useState(false);
  const roleBeforeEdit=useRef(profile.designation),cheatIssued=useRef(false);
  useEffect(()=>{if(cheatIssued.current && milestones.length===15){cheatIssued.current=false;document.getElementById('milestone-title')?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}},[milestones]);
  const currentProfile=useRef({profileId,profile,setProfile});currentProfile.current={profileId,profile,setProfile};
  const today=localDay(Date.now()),[followToday,setFollowToday]=useState(true);
  useEffect(()=>{if(followToday)setDate(today);},[today,followToday]);
  const selected=rows.filter(row=>inPeriod(row.day,period,date)), app=selected.reduce((sum,r)=>sum+r.appMs,0),coding=selected.reduce((sum,r)=>sum+r.codingMs,0);
  const projects=new Map<string,{name:string;app:number;coding:number}>();selected.forEach(r=>{const p=projects.get(r.projectId)||{name:r.projectName,app:0,coding:0};p.app+=r.appMs;p.coding+=r.codingMs;projects.set(r.projectId,p);});
  const update=(patch:Partial<LocalProfile>)=>setProfile({...profile,...patch});
  const exportCsv=()=>{const quote=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const data=[['Date','Project','Active app seconds','Active coding seconds','First coding','Last coding'],...selected.map(r=>[r.day,/^[=+@-]/.test(r.projectName)?`'${r.projectName}`:r.projectName,Math.round(r.appMs/1000),Math.round(r.codingMs/1000),r.firstCoding?new Date(r.firstCoding).toLocaleString():'',r.lastCoding?new Date(r.lastCoding).toLocaleString():''])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`eQc_Time_${period}_${date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  async function photo(file:File|undefined) { if(!file)return;const requestedProfile=profileId;setPhotoError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setPhotoError('Choose a PNG, JPEG or WebP image smaller than 2 MB.');return;}try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,256/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();if(currentProfile.current.profileId===requestedProfile)currentProfile.current.setProfile({...currentProfile.current.profile,photo:canvas.toDataURL('image/png')});}catch{setPhotoError('This photo could not be opened. Choose another image.');}}
  return <main className="panel profile-panel"><header className="profile-heading"><div><h2>Profile & time</h2><p>Personal details and time records stay on this computer. Your name is also used for coding and LAN sessions.</p></div><button onClick={onClose}>Back to Workspace</button></header>
    {error && <p role="alert">{error}</p>}
    <fieldset className="profile-columns" disabled={busy}><div className="profile-time-column"><section className="profile-time"><div className="profile-heading"><h3>Time overview</h3><button onClick={()=>update({paused:!profile.paused})}>{profile.paused?'Resume tracking':'Pause tracking'}</button></div><p>Tracking: <strong>{status}</strong>. Sessions pause after five idle minutes or when you leave the app. Coding time starts when you apply a code; after an idle break, apply another code to start again.</p>
      <div className="profile-controls"><label>Period <select aria-label="Period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option><option value="year">Yearly</option></select></label><label>Date <input type="date" value={date} onChange={e=>{setDate(e.target.value);setFollowToday(false);}}/></label><button onClick={()=>{setDate(today);setFollowToday(true);}}>Today</button><button onClick={exportCsv} disabled={!selected.length}>Export time CSV</button></div>
      <div className="profile-totals"><div><span>Active coding</span><strong>{duration(coding)}</strong></div><div><span>Active app time</span><strong>{duration(app)}</strong></div></div><p>Times are hours:minutes:seconds. Coding time is included in app time. Weeks run Sunday–Saturday; dates use this computer’s local time.</p>
      <div className="profile-table"><table><thead><tr><th>Project</th><th>Active coding</th><th>Active app time</th></tr></thead><tbody>{[...projects].map(([id,p])=><tr key={id}><td>{p.name}</td><td>{duration(p.coding)}</td><td>{duration(p.app)}</td></tr>)}</tbody></table></div>{!selected.length&&<p>No time recorded in this period yet.</p>}
      <details><summary>Daily records and coding times</summary><div className="profile-table"><table><thead><tr><th>Date</th><th>Project</th><th>Coding</th><th>App</th><th>First coding</th><th>Last coding</th></tr></thead><tbody>{[...selected].sort((a,b)=>b.day.localeCompare(a.day)).map(r=><tr key={`${r.day}-${r.projectId}`}><td>{r.day}</td><td>{r.projectName}</td><td>{duration(r.codingMs)}</td><td>{duration(r.appMs)}</td><td>{r.firstCoding?new Date(r.firstCoding).toLocaleTimeString():'—'}</td><td>{r.lastCoding?new Date(r.lastCoding).toLocaleTimeString():'—'}</td></tr>)}</tbody></table></div></details>
    </section>

    </div><div className="profile-details-column">    <section className="profile-details"><div className="profile-portrait-area"><div className="profile-portrait">{profile.photo?<img src={profile.photo} alt="Your profile"/>:<span>{profile.name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('').toUpperCase()||'👤'}</span>}</div><label>Profile picture<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void photo(e.target.files?.[0])}/></label>{profile.photo&&<button onClick={()=>update({photo:''})}>Remove photo</button>}{photoError&&<p role="alert">{photoError}</p>}</div><h3>My details</h3><div className="profile-switcher"><label>Active profile<select aria-label="Active profile" value={profileId} onChange={e=>{setDeleteConfirm(false);selectProfile(e.target.value);}}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name||'Unnamed profile'}{p.email?` · ${p.email}`:''} · {p.id.slice(-4)}</option>)}</select></label><div className="research-actions"><button onClick={addProfile}>New profile</button><button onClick={()=>setDeleteConfirm(true)}>Delete profile…</button></div></div><p>Last worked: {profiles.find(p=>p.id===profileId)?.lastWorkedAt ? new Date(profiles.find(p=>p.id===profileId)!.lastWorkedAt).toLocaleString() : 'No recorded session yet'}</p><div className="profile-fields">{(['name','email','designation','organization'] as const).map(field=><label key={field}>{({name:'Name',email:'Email',designation:'Role / designation',organization:'Organization'})[field]}<input type={field==='email'?'email':'text'} maxLength={200} value={profile[field]} onFocus={()=>{if(field==='designation')roleBeforeEdit.current=profile.designation;}} onChange={e=>{if(field==='designation'&&e.target.value.trim().toLowerCase()==='pikachu'){cheatIssued.current=true;update({designation:roleBeforeEdit.current});unlockMilestones();}else update({[field]:e.target.value});}} onBlur={e=>{if(field==='name')update({name:e.target.value.trim()});}}/></label>)}</div><div className="profile-bored"><button aria-pressed={profile.workspaceAnimations===true} title="Toggle playful animations when adding sources or subcodes, or deleting items" onClick={()=>update({workspaceAnimations:!profile.workspaceAnimations})}>Bored</button><span>Workspace animations: {profile.workspaceAnimations?'on':'off'}</span></div><p>Your name is shared with project coder and LAN names. The selected profile and its time records are included in JSON project backups. Existing coding keeps its recorded author.</p></section>
</div></fieldset>
    <ProfileMilestones key={profileId} awards={milestones} onSeen={markMilestoneSeen}/>
    {deleteConfirm && <div className="research-overlay" onKeyDown={e=>{if(e.key==='Escape')setDeleteConfirm(false);if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll<HTMLButtonElement>('button');const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey && document.activeElement===first){e.preventDefault();last?.focus();}if(!e.shiftKey && document.activeElement===last){e.preventDefault();first?.focus();}}}}><section className="project-export-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-profile-title"><h2 id="delete-profile-title">Delete profile?</h2><p>Delete {profile.name||'this unnamed profile'} and its saved time records on this computer? Your research projects and existing coding will remain.</p><div className="research-actions"><button autoFocus onClick={()=>setDeleteConfirm(false)}>Cancel</button><button onClick={()=>{deleteProfile();setDeleteConfirm(false);}}>Delete profile</button></div></section></div>}

  </main>;
}
