import React, { useState } from 'react';
const KEY='eqc-preferred-reader-fonts';
const standard=[['Cambria',"Cambria, Georgia, 'Times New Roman', serif"],['Caladea',"'Caladea', Cambria, Georgia, serif"],['Georgia','Georgia, serif'],['Times New Roman',"'Times New Roman', serif"],['Arial','Arial, sans-serif'],['Verdana','Verdana, sans-serif'],['Calibri','Calibri, sans-serif'],['Courier New',"'Courier New', monospace"],['Kalpurush',"'Kalpurush', 'SolaimanLipi', 'Nirmala UI', 'Segoe UI', sans-serif"],['SolaimanLipi',"'SolaimanLipi', 'Kalpurush', 'Nirmala UI', 'Segoe UI', sans-serif"],['Siyam Rupali',"'Siyam Rupali', 'Kalpurush', 'SolaimanLipi', 'Nirmala UI', sans-serif"],['Nikosh',"'Nikosh', 'Kalpurush', 'SolaimanLipi', 'Nirmala UI', sans-serif"]];
const family=(name:string)=>`"${name.replace(/\\/g,'\\\\').replace(/"/g,'\\"')}", sans-serif`;
function readFonts():string[]{try{const names=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(names)?names.filter(n=>typeof n==='string'&&n.length<=80).slice(0,50):[];}catch{return [];}}
export default function ReaderFontPicker({value,onChange}:{value:string;onChange:(font:string)=>void}){
  const [fonts,setFonts]=useState(readFonts),[adding,setAdding]=useState(false),[name,setName]=useState(''),[error,setError]=useState('');
  const custom=fonts.find(n=>family(n)===value),known=!value||standard.some(([,v])=>v===value)||!!custom;
  const save=(next:string[])=>{try{localStorage.setItem(KEY,JSON.stringify(next));setFonts(next);setError('');return true;}catch{setError('Your font preference could not be saved.');return false;}};
  const add=()=>{const trimmed=name.trim();if(!trimmed)return;if(fonts.length>=50&&!fonts.includes(trimmed)){setError('Remove a preferred font before adding another.');return;}const next=[...new Set([...fonts,trimmed])];if(save(next)){onChange(family(trimmed));setName('');setAdding(false);}};
  return <div className="reader-font-picker"><select title="Reading font" aria-label="Reading font" value={value} onChange={e=>onChange(e.target.value)}><option value="">Font (default)</option><optgroup label="Standard fonts">{standard.map(([label,v])=><option key={v} value={v}>{label}</option>)}</optgroup>{fonts.length>0&&<optgroup label="My fonts">{fonts.map(n=><option key={n} value={family(n)}>{n}</option>)}</optgroup>}{!known&&<option value={value}>Saved font</option>}</select><button onClick={()=>setAdding(v=>!v)} aria-expanded={adding}>Add font…</button>{custom&&<button onClick={()=>{if(save(fonts.filter(n=>n!==custom)))onChange('');}} title="Remove this font from My fonts">Remove font</button>}{adding&&<div className="reader-font-add"><label>Installed font name<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}if(e.key==='Escape')setAdding(false);}} placeholder="e.g. Aptos, Noto Sans Bengali"/></label><p>Enter the name of a font installed on this computer. Install new font files through your operating system first. This changes the coding text view.</p><button onClick={add} disabled={!name.trim()}>Use font</button></div>}{error&&<p role="alert">{error}</p>}</div>;
}
