name: Build and Release eQc

on:
  push:
    tags:
      - 'v*'

# THIS IS THE MAGIC KEY TO UPLOAD FILES:
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Force install Mac DMG License builder
        if: runner.os == 'macOS'
        run: npm install dmg-license --no-save

      - name: Build and Publish Electron app
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          